### ISSUE TITLE
make sheet take action of scroll not collection view

### ISSUE THREAD

**Issue by mohamedshaat** [hryk224/Bottomsheet#6]
i want when scroll collection view sheet take action

**Comment by hryk224** [comment]
@mohamedshaat 
Supported by v1.4.0 #7 

You can use `isScrollEnabledInSheet` argument in `func addCollection(:)`.

```Swift
func addCollectionView(isScrollEnabledInSheet: Bool,
 flowLayout: UICollectionViewFlowLayout?,
 configurationHandler: ((UICollectionView) -> Void))
```

`isScrollEnabledInSheet: false`

![f512377864996135738e254b41d77665](https://cloud.githubusercontent.com/assets/2265513/23213050/d3cdb9f8-f94c-11e6-9749-00511967c032.gif)
